### ISSUE TITLE
libcxx didn't get an autotick for llvm release 10.0

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/libcxx-feedstock#54]
# Issue:

llvm-project released llvmorg-10.0.0 a few weeks back.  libcxx didn't get an autotick PR.

# Suspected Cause:

`recipe/meta.yaml` fails to use `{{ version }}` [in two places where it needs to](https://github.com/conda-forge/libcxx-feedstock/blob/b0287d4e2aa07dbe91ba59ac782b3e6d3734a8ef/recipe/meta.yaml#L8-L14).

```
source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/libcxx-{{ version }}.src.tar.xz
    sha256: 0981ff11b862f4f179a13576ab0a2f5530f46bd3b6b4a90f568ccc6a62914b34
    patches:
      # See https://bugs.llvm.org/show_bug.cgi?id=39696
      - ppc64le-constexpr.patch  # [ppc64le]

  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/libcxxabi-{{ version }}.src.tar.xz  # [linux]
    sha256: e8f978aa4cfae2d7a0b4d89275637078557cca74b35c31b7283d4786948a8aac  # [linux]
    folder: libcxxabi  # [linux]
```

The URL lines need to use `llvmorg-{{ version }}` where they currently use `llvmorg-9.0.1` and I think the autotick bot will figure out the autotick PR.

# Proposed Fix:

Rather than have a separate PR to fix this and wait for an autotick for 10.0, I'm going to just submit a manual bump to 10.0 that also fixes this.
